### ISSUE TITLE
Mejorar la página de activar cuenta

### ISSUE THREAD

**Issue by germanescobar** [makeitrealcamp/start#413]
Algunas mejoras a la pantalla de activar cuenta:

1. Explicarle para qué se usa el nickname.
2. No preguntarle visibilidad del perfil ni género, esa información la estamos ingresando al crear al usuario (el género se lo podemos pedir si no lo tenemos).
3. Los campos de la contraseña son más pequeños que los demás.
4. Date picker para la fecha de cumpleaños o al menos explicar en qué formato.
4. Yo lo dejaría todo en una columna en el siguiente orden:
  * Correo electrónico (deshabilitado)
  * Contraseña
  * Confirmar contraseña
  * Fecha de cumpleaños.
  * Teléfono móvil.
5. Pedir el indicativo en el celular para poder recibir alumnos de otros paises.

**Comment by nmenag** [comment]
fix #420
