### ISSUE TITLE
Revisión a la evaluación de quizzes

### ISSUE THREAD

**Issue by germanescobar** [makeitrealcamp/start#433]
Supongamos que creamos un quiz con una única pregunta que tiene una respuesta correcta y 4 incorrectas. Cuando intento el quiz y no selecciono nada, mi puntaje es de 80%, que no tiene sentido porque no marqué la solución correcta.

¿Cómo podríamos mejorar este problema?

**Comment by germanescobar** [comment]
@simon0191 ¿qué tal si hacemos un cambio sobre la evaluación? Mi propuesta sería la siguiente: por cada item marcado correctamente se le agrega un punto, y por cada uno marcado incorrectamente se le resta un punto. De esta forma, si el estudiante marca uno bien y uno mal tiene 0 puntos. Si deja de marcar uno que debía haber seleccionado se le resta un punto.

Obviamente no le vamos a dar puntos negativos, si la suma de los correctos e incorrectos es menor a 0, pues es 0.

¿Qué opinas?

**Comment by simon0191** [comment]
@germanescobar mejor implementar la pregunta de única respuesta, no?

**Comment by germanescobar** [comment]
Se implementó única respuesta y se simplificó la evaluación de la múltiple respuesta (1 si está correcto, 0 si falló en al menos alguna respuesta).
