### ISSUE TITLE
Denegar acceso a recursos a los que no tienen acceso los usuarios por el programa al que están inscritos

### ISSUE THREAD

**Issue by simon0191** [makeitrealcamp/start#465]
En este momento cualquier estudiante puede acceder a cualquier curso, reto o recurso sin importar que el estudiante no esté inscrito en un programa que le de acceso al curso, reto o recurso. Lo único que le impide el acceso es que los cursos a los que no debería tener acceso no aparecen listados en "temas", sin embargo, sin embargo si copia y pega el link va a poder ver el curso.

**Comment by nmenag** [comment]
¿Esto no se soluciona con el inicio de sesión por Slack?, por que si ya están en slack es por que ya pagaron por el programa ¿no?
