### ISSUE TITLE
Guardar y buscar los usuarios por correo sin tener en cuenta mayúsculas/minúsculas

### ISSUE THREAD

**Issue by simon0191** [makeitrealcamp/start#466]
- Cuando se cree un usuario se debe guardar el correo en minúsculas. Por ejemplo, si se crea un usuario con el correo `PepePerez@mail.com`, en la base de datos debe quedar como `pepeperez@mail.com`

- Si al momento de autenticarse, el servicio de autenticación retorna el correo con mayúsculas, se debe buscar el correo sin tener en cuenta mayúsculas/minusculas

**Comment by nmenag** [comment]
Lo mismo, ¿eso no se soluciona con la autenticación de Slack?, ya no se esta pidiendo un email y una contraseña para ingresar.

**Comment by germanescobar** [comment]
No, porque todavía se crea el usuario manualmente antes de darle acceso a Slack. La razón es que también ahora hay la opción de crear usuarios que entren con usuario y contraseña.
