### ISSUE TITLE
Rutas que valida el evaluador en el reto de Rails I: Creando actores

### ISSUE THREAD

**Issue by hackvan** [makeitrealcamp/start#618]
Algo que sucede con el reto (versión de ruby: 2.4.1 y rails: 5.0.2) es que utilizando el mapeo manual en el archivo config.rb:

`get '/actors/new', to: 'actors#new'`

rails genera por defecto la ruta:

`actors_new_path`

pero si se define la ruta con resources:

`resources :actors, only: [:index, :new, :create]`

este crea por defecto la ruta:

`new_actor_path`

el evaluador del reto siempre busca la ruta `new_actor_path` así que obliga para la solución o bien utilizar siempre `resources` para esa ruta o sino colocar un alias en la ruta hecha con `get` como:

`get '/actors/new', to: 'actors#new', as: :new_actor`

para que sea valida la evaluación.

**Comment by germanescobar** [comment]
Solucionado!
